### ISSUE TITLE
conversion 

### ISSUE THREAD

**Issue by enweazudaniel** [JolomonSon/Student-Study-Portal#4]
![Screenshot 2022-05-14 160628](https://user-images.githubusercontent.com/29769483/168433336-9880c6ac-98ef-445a-8d9f-4149156b3519.png)
Length unit doesn't change (stays as "yard")

**Comment by JolomonSon** [comment]
This is noted!
Thanks for the observation

**Comment by preciousimo** [comment]
Bug fixed! John update production.
